services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 8632:2368
    # see https://ghost.org/docs/config/#configuration-options
    database:
      {
        client: sqlite3,
        connection: { filename: db-dev/notes-dev.db },
        useNullAsDefault: true,
        debug: false,
      }
      # this url value is just an example, and is likely wrong for your environment!
    url: http://localhost:8632
    NODE_ENV: development
    volumes:
      - ghost:/var/lib/ghost/content

volumes:
  ghost:
