services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 8632:2368
    environment:
      - database__client=sqlite3
      - database__connection__filename=/var/lib/ghost/content/notes-dev.db
    volumes:
      - ghost:/var/lib/ghost/content
      - db-dev:/var/lib/sqlite3

volumes:
  ghost:
  db-dev:
